name: Compresser site web en Brotli
on: push

jobs:
  compress:
    name: Brotli
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Compress assets
        uses: dave-mcconnell/brotli-action@v1
        with:
          args: '-Zkv *.html depot/*.html depot/recettes/*.html css/*.css js/*.js *.xml *.txt'
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ${{ github.workspace }}
