name: Compresser site web en Brotli
on: push

# pre-compress static assets with gzip and brotli with tools: 'brotli,gzip'
- name: Compresser Fichiers Statiques
  uses: stefh/ghaction-CompressFiles@v1
  with:
    path: ${{ env.PUBLISH_DIR }}
    extensions: '.js,.css,.html,.xml,.txt,.md'
    depth: 3
    tools: 'brotli'
