- name: Compresser Fichiers Statiques en Brotli
  uses: stefh/ghaction-CompressFiles@v1
  with:
    path: ${{ env.PUBLISH_DIR }}
    extensions: '.js,.css,.html,.xml,.txt,.md'
    depth: 3
    tools: 'brotli'
